### ISSUE TITLE
doubt - design

### ISSUE THREAD

**Issue by luizhenriquesoares** [Significa/frontend-challenge#1]
I have to do the react app, based on design proposed,? or i can build app, with my design thinkgs?

**Comment by pdrbrnd** [comment]
@luizhenriquesoares this challenge is only intended to let us evaluate how people handle some of the tasks we do on a daily basis (dealing with external APIs, promises, ...).
You don't have to base the app on the design proposed at all, feel free to come up with whatever you like!
Also, if you already have something built that checks all of these requirements feel free to send it over. There's no need on building something new just for this challenge.
