### ISSUE TITLE
Job position

### ISSUE THREAD

**Issue by ikarofelix** [Significa/frontend-challenge#34]
Github recommended me this repo, I want to do the challenge, but haven't found anything about the position post or something like that. Went to your website and only found this: https://significa.co/careers, the only job position is for a senior front-end developer.

I would like to know more about the position and if it's still opened for this challenge so I can be a part of it. Is the job remote? I'm from Brazil, if it's on-site and I got selected, I would be open to move out to Portugal. Looking forward to your answer.

Thanks!

**Comment by pdrbrnd** [comment]
hey @ikarofelix thank you for your interest!
Yes, unfortunately we are only looking for senior applications at the moment.

As for remote, even tho we are a remote-friendly agency – some team members are 100% remote – we do prefer some close contact from time to time (also depending on the seniority and need for support and/or mentoring). We sponsored visas from Brazil in the past but it's on a case-by-case basis so, in these cases, I recommend reaching out via e-mail.

Let me know if you have any more questions :)
